### ISSUE TITLE
Include a wind turbine tag field

### ISSUE THREAD

**Issue by lejeunemax** [IEAWindSystems/windIO#102]
Support for wind turbine ID / tags would be a nice addition. This could be quite easily achieved by adding an optional ```tags``` field to the layout description. 

```
  layouts:
    description: Position of wind turbines. Supports single or multiple layouts.
    oneOf:  # Allow either single layout as an object or multiple layouts as an array
      - type: object
        required:
          - coordinates
        optional:
          - tags
        additionalProperties: false
        properties:
          coordinates:
            description: List of turbine coordinates for this layout
            $ref: "common.yaml#/definitions/coordinates"
          tags:
            description: List of turbine id/tags
            type: array
            items:
              type: str
            optional: true
```
