### ISSUE TITLE
Type out beam properties

### ISSUE THREAD

**Issue by kenloen** [IEAWindSystems/windIO#37]
The current version of the beam properties for the `six_x_six` is using 2D arrays with a shape of  *N x 21* for the `stiff_matrix` and `inertial_matrix`. I would suggest to type out the components instead similar to what is done for `timoschenko_hawc` and `cp_lambda_beam`. 

I think the current format is great for reading the beam data into a numpy array, but for manually inspecting the data it is not that easy to find the bending stiffness for the flapwise direction as one have to count the number of columns and remember which column number is correspond to. I think a big part of the windIO formats is it is human readable data, which I think this change would support a more human readable format.

A suggestion for should a change could be:
```yaml
stiff_matrix:
  ....
  values:
    S11: [..]
    S12: [..]
    ....
    S21: [..]
    S22: [..]
   ....
    S66: [..]
inertia_matrix:
  ....
  values:
    m: [..]
    x_cm: [..]
    y_cm: [..]
    iedge: [..]
    icp: [..]
    iflap: [..]
    iplr: [..]
```
Where I have assumed that for the `inertia_maxtix` the matrix is not a full *6x6* which I am not sure is generally true?!

Any comments and suggestions are much welcome.
