### ISSUE TITLE
Specification of flooded members

### ISSUE THREAD

**Issue by fabiopierella** [IEAWindSystems/windIO#76]
Hello,

a quick question from my side. I could not find where in the [WindIO taxonomy](https://windio.readthedocs.io/en/latest/source/floating.html#) one defines whether a floater member is flooded or not.

Thanks for any help you may provide.

Best,
Fabio

**Comment by gbarter** [comment]
A simple `flooded=True` flag does not currently exist, but is a good suggestion for something to add to the ontology.  For now, you would add ballast that takes up the full volume of the member.  Something like:
```
ballasts:
   - variable_flag: False
     material: ocean_water
     volume: 12345
     grid: [0.0, 1.0]
```
Where you would define `ocean_water` in the list of materials and the volume would be the internal volume of the member, so a bit more work than a simple flag, but should do the trick.
