### ISSUE TITLE
Material fatigue properties

### ISSUE THREAD

**Issue by peter-greaves** [IEAWindSystems/windIO#88]
It would be good to add material fatigue properties (constant life diagram for composites, SN curve for metals) to the material data as many parts of modern wind turbine design are driven by fatigue.

**Comment by fzahle** [comment]
Hi Peter,
Please review the entries here:

https://github.com/IEAWindSystems/windIO/blob/4f8491f0ebe44956c02f82555c9a94f0a9329a07/windIO/turbine/IEAontology_schema.yaml#L2303

and we'd welcome proposal of additional properties. You can list them here and we can add them to the schema.

**Comment by peter-greaves** [comment]
This is a good format for composites, but for something general to steel and composites all I can think is to have an array with columns N (number of cycles), R (R-value), A (stress/strain value at N) and m (slope). Composites could then be defined on a row/R value but with only one value of A for N=1, whereas steel could be defined with 3 rows showing how the slope and intercept change as the number of cycles increases, and the endurance limit could be given with m = inf. But I recognise this format is less nice! It could maybe work just adding another variable N rather than doing it as an array?

**Comment by ptrbortolotti** [comment]
I will come up with a proposal in a new PR as soon as PR #87 is completed and merged in

**Comment by ptrbortolotti** [comment]
ok I've given this issue some thoughts and I think I understand the limitation.
today, `m`, `R`, and `A` are either floats or 3-value arrays (to specify 3-values for R, such as -1, 0.1, and 10)

so either:
```yaml
-  name: glass_uni
    R: -1
    m: 10
    A: 8e+8
```

or

```yaml
-  name: glass_uni
    R: [-1, 0.1, 10]
    m: [10, 10, 10]
    A: [6e+8, 8e+8, 5e+8]
```

**SOLUTION 1**
we could change this definition and make it multi-dimensional. that could look like this:

```yaml
-  name: glass_uni
    fatigue:
         - R:-1
            m: 10
            A: 6e+8
            # leave N field out
         - R: 0.1
            m: 10
            A: 8e+8
            # leave N field out
-  name: steel_tower
    fatigue:
         - R:-1
            N: [1.e+5, 1.e+6, 1.e+7, 1.e+8, 1.e+9]
            A: [4e+8, 3e+8 2e+8, 1.5e+8, 1.4e+8]
            # leave m field out
```


**SOLUTION 2**
or we could favor simplicity over generality and stick to arrays, where the dimension is either R or N, something like:

```yaml
-  name: glass_uni
    R: [-1, 0.1, 10]
    m: [10, 10, 10]
    A: [6e+8, 8e+8, 5e+8]
    # leave N field out

-  name: steel_tower
    N: [1.e+5, 1.e+6, 1.e+7, 1.e+8, 1.e+9]
    A: [4e+8, 3e+8 2e+8, 1.5e+8, 1.4e+8]
    # leave m field out
    R:-1 # if N is defined, only one value of R is allowed

```

@peter-greaves @fzahle @ecamare any preference?
