### ISSUE TITLE
Re-structuring of outer_shape_bem and airfoils sections

### ISSUE THREAD

**Issue by ptrbortolotti** [IEAWindSystems/windIO#93]
Right now the `x`, `y`, and `z` fields of the reference axis each comes with `grid` and `values` sub-fields.
```
reference_axis:
                x:
                    grid: [0.0, 0.1, ..., 1.0]
                    values: [0.0, -0.5, ..., -5.0]
                y:
                    grid: [0.0, 1.0]
                    values: [0.0, 1.0]
               z:
                    grid: [0.0, 0.1, ..., 1.0]
                    values: [0.0, 10., ..., 100.0]
```

On one side, this allows user to set three different grids, which is convenient for straight components such as the `tower` and the `monopile`.
At the same time, most solvers will require `x`, `y`, and `z` on a common grid, and therefore immediately interpolate.

@michaelasprague and @deslaughter at NREL are suggesting to switch to a common grid

```
reference_axis:
                grid: [0.0, 0.1, ..., 1.0]
                x:  [0.0, -0.5, ..., -5.0]
                y: [0.0, 0.0, ..., 0.0]
                z: [0.0, 10., ..., 100.0]
```

I'm tempted to agree with @michaelasprague and @deslaughter

This would be consistent with the new beam definition, where K and I entries are defined on a common grid, see here https://github.com/IEAWindSystems/windIO/blob/61a5fe94aa2172797bf676cb14efdf9417128768/windIO/converters/v2p0/IEA-15-240-RWT.yaml#L325

**Comment by ptrbortolotti** [comment]
@kenloen @fzahle what do you think?

**Comment by kenloen** [comment]
I do agree that it can be somewhat redundant to add the `grid` entry for all, and it makes sense that the reference axis is a unit where having arbitrary grids could be redundant.

**Comment by fzahle** [comment]
I agree that it would be convenient, since indeed, most tools immediately interpolate onto a common grid. But the same can be said for the entire planform, where quantities such as chord, twist and relative thickness are often defined on the same grid, and in a tool definitely needs to be. The convenience of individual grids primarily relates to human specified quantities where

```
    grid: [0., 1.]
    values: [0.0, 0.0]
```

is quick to add manually, but isn't really relevant for the planform. And often we anyway generate the windIO file programmatically where it's just as easy to use np.linspace, np.zeros etc. 

For the internal structure there are better arguments for keeping individual grids, since layers also have different spanwise extents. But a common error in windIO files is that thickness is defined according to one grid, say [0.1, 0.9] while width, fiber_orientation etc is wrongly specified with grid [0., 1.]. So I would for sure support that we should elevate grid to be common for all quantities in a layer to remove this common source of mistakes.

So my point is, if you want to discuss grids, I think we should reconsider the use of grid across all turbine geometric quantities.

**Comment by gdw2024** [comment]
Same grid for outer geometry (twist, chord, blade_axis) is fine, as that data is typically generated.

But not for the layup. Layup should only have the definitions, not interpolated data in grid points not relevant to the definition.

The main idea of yaml format is that it is human-friendly in terms of readability.

**Comment by fzahle** [comment]
At yesterday's windIO working group meeting we agreed to go ahead with a single grid for the reference_axis, as well as another one for outer_shape_bem twist, chord, rthick, section_offset_*, but keep individual grids for internal structural layers and individual items within a layer definition (thickness, fiber_orientation etc).

**Comment by fzahle** [comment]
It feels like windIO 2.0 allows for bigger and more backward incompatible changes, and if there's no "holy cows", here's a re-structuring of the turbine geometry/aero definition that I think addresses some of the challenges we have with geometric, BEM and beam structural definitions:

```yaml
components: 
  blade: 
    geometry: 
      airfoil_position: # airfoils referenced here should be listed in blade.geometry.airfoils
        grid: [0.0, 0.02, 0.04920081991795748, 0.07013327924329996, 0.08896317384001168, 0.108027202862074, 0.11574083215898802, 0.13802574757253655, 0.16993873755142214, 0.2359792301508176, 0.39263476388725566, 0.4934777452516964, 0.6068258305820773, 0.74, 0.8769320450757272, 0.96, 1.0]
        labels: ['circular', 'circular', 'FB90', 'FB80', 'FB70', 'FB60', 'SNL-FFA-W3-560FB', 'SNL-FFA-W3-480FB', 'SNL-FFA-W3-420FB', 'FFA-W3-360', 'FFA-W3-330blend', 'FFA-W3-301', 'FFA-W3-270blend', 'FFA-W3-241', 'FFA-W3-241', 'FFA-W3-211', 'FFA-W3-211']
      planform:
        grid: [0., 0.5, 1.]
        chord: [5.8, 3.5, 1.0]
        twist: [12.0, 3.5, -2.0]
        section_offset_x: [2.9, 1., 0.5]
        section_offset_y: [0., 0., 0.]
        rthick: [1., 0.35, 0.24]
      reference_axis:  # see 1) below
        grid: [0., 0.5, 1.]
        x: [0., 0.5, 6.2]
        y: [0., 0., 0.]
        z: [0., 70., 140]
      airfoils:  # For BEM-only usage this section isn't required
        - name: FFA-W3-241
          rthick: 0.241
          coordinates:
            x:
            y:
        - name: ...
      surface:  # For BEM-only usage this section isn't required
        grid: []
        x:
        y:
        z:
    aero:
      stall_margin:  # and other aero-quantities
        grid: [0., 0.3, 0.7, 1.0]
        values: [3.0, 3.0, 2.0, 2.0]
      polars: # airfoils referenced here should be listed in blade.aero.airfoil_data
        grid: [0.0, 0.2359792301508176, 0.39263476388725566, 0.4934777452516964, 0.6068258305820773, 0.74, 0.8769320450757272, 0.96, 1.0]
        values:
          - name: 'circular'
            index: 0  # see 3) below
          - name: 'FFA-W3-360'
            index: 0
          - name: 'FFA-W3-330blend'
            index: 0
          - name: 'FFA-W3-301'
            index: 0
          - name: 'FFA-W3-270blend'
            index: 0
          - name: 'FFA-W3-241'
            index: 0
          - name: 'FFA-W3-241'
            index: 0
          - name: 'FFA-W3-211'
            index: 0
          - name: 'FFA-W3-211'
            index: 0
      airfoil_data:
        - name: FFA-W3-241
          polars:
            - configuration: 70% free transition, 30% fully turbulent
              re: 10000000.0
              grid: [-180., 0., 180.]
              cl: [0., 1.2, 0.]
              cd: [0.5, 0.002, 0.5]
              cm: [0.2, 0.2, 0.2]
            - configuration: soiled
              re: 10000000.0
              grid: [-180., 0., 180.]
              cl: [0., 1.2, 0.]
              cd: [0.5, 0.003, 0.5]
              cm: [0.2, 0.2, 0.2]
    elastic_properties_mb: 
      six_x_six:
        grid: [0., 0.5, 1.0]
        # See 2) below
        offset_x:
        offset_y:
        twist: [0., 0., 0.]
        stiff_matrix:
        inertia_matrix:
```
1)  we could also place the x, y, z coordinates on the same grid as planform and do away with reference_axis?
2) I've removed reference axis from the `six_x_six` since if a user specifies an axis different from the `reference_axis` defined in the geometry section it's a non-trivial task to compute its relative position to this axis. Rather have one single truth for the reference axis and then define offsets for which we can clearly define in which reference frame these offsets are defined.
3) having a polar index is not exactly an intrinsic property but allows us to specify a default polar from a series of available ones.

This should also address the point made in #15 and the `aero_properties` suggested in #89 including #49 could be included in the `aero` section.

I haven't yet tried to code a parser for this changed format yet, so could need more tweaking. But it feels like now is the time to suggest major changes to the format, and not hold back to preserve compatibility, so here it is :-)

@WillC-DNV @jelmermc would love for you to also chime in to this discussion.

**Comment by ptrbortolotti** [comment]
To address #15, can't the user simply define many airfoils, all with `x` and `y` and some also with the `polars`? I've just checked the latest schema and the properties `polars` or `aerodynamic_center` are not required. The converters could then check where polars are provided

At NREL we are good with a single `reference_axis` with a single `grid` and `x`, `y`, `z`. I will work on updating the v1.0 to v2.0 converter

In addition to the changes, we also need to be more explicit about the order of operations to build the model. I went back to an old email from @RiekeJ that listed these steps:

1.	From the master airfoils, use PCHIP to obtain distribution of relative thickness
2.	Scale airfoils by chord
3.	In the blade root coordinate system, apply section_offset_x from the leading edge
4.	In the blade root coordinate system, apply section_offset_y from the chord line
5.	Apply twist with respect to the new airfoil center
6.	Apply x and y translations from the curved reference axis
7.	In 3D, rotate airfoil to be orthonormal to 3D axis (maybe only with respect to prebend?)

However, one could say that steps 4/5/6 should happen in the plane orthonormal to the 3D reference axis. @fzahle thoughts?

This post follows a discussion with @michaelasprague and @deslaughter

**Comment by fzahle** [comment]
@ptrbortolotti 

> To address [#15](https://github.com/IEAWindSystems/windIO/issues/15), can't the user simply define many airfoils, all with `x` and `y` and some also with the `polars`? I've just checked the latest schema and the properties `polars` or `aerodynamic_center` are not required. The converters could then check where polars are provided
> 

We definitely could describe that as an option to address this issue, but the restructuring tries to separate geometry from the `_bem` part, since the link between airfoil shape and polars are not relevant to for example structural modellers or hi-fidelity CFD modellers, and oppositely, BEM modellers don't really care about the airfoil shape but only the polars. I think the reasoning back when it was made this way was that it was an "airfoil database" where shape and polar are directly linked.

> At NREL we are good with a single `reference_axis` with a single `grid` and `x`, `y`, `z`. I will work on updating the v1.0 to v2.0 converter
> 

Great, maybe we should conclude about the rest of the restructuring before implementing it in the converter.

> In addition to the changes, we also need to be more explicit about the order of operations to build the model. I went back to an old email from [@RiekeJ](https://github.com/RiekeJ) that listed these steps:
> 
> 1. From the master airfoils, use PCHIP to obtain distribution of relative thickness
> 2. Scale airfoils by chord
> 3. In the blade root coordinate system, apply section_offset_x from the leading edge
> 4. In the blade root coordinate system, apply section_offset_y from the chord line
> 5. Apply twist with respect to the new airfoil center
> 6. Apply x and y translations from the curved reference axis
> 7. In 3D, rotate airfoil to be orthonormal to 3D axis (maybe only with respect to prebend?)
> 
> However, one could say that steps 4/5/6 should happen in the plane orthonormal to the 3D reference axis. [@fzahle](https://github.com/fzahle) thoughts?

Definitely important to define particularly for structural modelling and 3D CFD. We normally don't use `airfoil_position` to construct relative thickness but more often the `rthick` distribution also allowed in windIO. But we probably need to take a tough choice and define that only one of the two is allowed. For steps 5 and 7 we construct a rotation matrix that applies rotations in three directions to place the airfoil orthonormal to the reference axis. A correction to the twist needs to be computed for more complex blade shapes with combined sweep and prebend. We should formally define this procedure in the docs, and I'd be happy to pick that up. I'll create an issue for this specific task.

**Comment by fzahle** [comment]
I've updated the suggested `elastic_properties_mb.six_x_six` removing offsets and twist since the local reference frame in which elastic properties are defined in should be one single "truth" defined by the procedure for lofting blades. `elastic_properties_mb` should perhaps have its own issue where we hash out the definition that can then be copy-pasted into the docs?

**Comment by kenloen** [comment]
I really like the idea of reorganizing the things such that names in components also reflect aspects of the components that are intrinsic, such as the geometry and what is modelling specific. Even though the blade is the discussion here, I think it would make sense to think about a consistent way that can be applied for all components. 

I would therefore suggest a format like below:

```yaml
components:
    blade:
        reference_axis: 
            grid: [0, .., 1]
            x: [...]
            y: [...]
            z: [...]
        assembly:
            length: 280
            mass: 1e6
            # Should there be more here?
        outer_shape:
            cross_sections: # This section should use the same grid as the ref-axis
                chord: [...]
                twist: [...]
                section_offset_x: [...]
                section_offset_y: [...]
                cs_shapes_position: ['circular', ...]
                cs_shapes: # `airfoils` would be a super set of this one and it could be referenced from here
                    -   name: FFA-W3-241
                        rthick: 0.241
                        coordinates:
                            x: [1, .., 1]
                            y: [0, .., 0]
                    -   name: ...
                rthick: [...]
            mesh: # Could simply defined a structured grid (as below) or be an external file format following a naming convention in our schema
                grid: []
                x: # 2D array
                y:
                z:
        aero:
            stall_margin:  # and other aero-quantities
                grid: [0., 0.3, 0.7, 1.0]
                values: [3.0, 3.0, 2.0, 2.0]
            polars: 
                grid: [0.0, 0.2359792301508176, 0.39263476388725566, 0.4934777452516964, 0.6068258305820773, 0.74, 0.8769320450757272, 0.96, 1.0]
                values:
                -   name: 'circular'
                    index: 0  # see 3) below
                -   name: FFA-W3-241
                    interp: # An option for interpolation could be added?
                        -   index: 0
                            weight: 0.2
                        -   index: 1
                            weight: 0.8
                        -   ...
                -   ...
            airfoils:
                -   name: FFA-W3-241
                    rthick: 0.241
                    coordinates:
                        x: [1, .., 1]
                        y: [0, .., 0]
                    polars:
                        -   configuration: 70% free transition, 30% fully turbulent
                            re: 10000000.0
                            grid: [-180., 0., 180.]
                            cl: [0., 1.2, 0.]
                            cd: [0.5, 0.002, 0.5]
                            cm: [0.2, 0.2, 0.2]
                        -   ...
        structure:
            cross_sections: # What is in the internal_structure_2d_fem but without the ref-axis
                webs: ...
                layers: ...
            beam_properties:
                solver: "Beam property solver" # a name or an id for a solver
                stiff_matrix: # What is in elastic_properties_mb.stiff_matrix currently
                    K11: ...
                inertia_matrix: # What is in elastic_properties_mb.inertia_matrix currently
                    mass: ...
            fem: # Some kind of fem mesh that can that can be made a schema for
    hub:
        reference_axis: 
            grid: [0, .., 1]
            x: [...]
            y: [...]
            z: [...]
        assembly:
            diameter: 5
            cone_angle: 4
        outer_shape:
            cross_sections: # This section should use the same grid as the ref-axis
                diameter: [...]
                twist: [...]
                section_offset_x: [...]
                section_offset_y: [...]
                cs_shapes_position: [ellipse, ...]
                cs_shapes: 
                    -   name: ellipse
                        rthick: 1.0
                        coordinates:
                            x: [1, .., 1]
                            y: [0, .., 0]
                    -   name: ...
                rthick: [...]
            mesh: # Could simply defined a structured grid (as below) or be an external file format following a naming convention in our schema
                grid: []
                x: # 2D array
                y:
                z:
        aero:
            drag_coefficient: 0.5
        structure:
            cross_sections: # What is in the internal_structure_2d_fem but without the ref-axis
                webs: ...
                layers: ...
            beam_properties:
                solver: "Beam property solver" # a name or an id for a solver
                stiff_matrix: # What is in elastic_properties_mb.stiff_matrix currently
                    K11: ...
                inertia_matrix: # What is in elastic_properties_mb.inertia_matrix currently
                    mass: ...
            fem: # Some kind of fem mesh that can that can be made a schema for
    ...
```

It implicitly assumes that the `reference_axis.grid` is the grid used across all.

Any thoughts on that?

**Comment by ptrbortolotti** [comment]
I like it. I think I'd need an example to try out in WISDEM/WEIS and verify that everything clicks in successfully. same for issue #31 !

**Comment by fzahle** [comment]
I think we're very close to something final, but I'd like to separate `outer_shape` from `aerodynamics`. This also allows us to use `outer_shape` for other sub-components, e.g. tower or nacelle, for which the shape is by no means aerodynamic. 

```yaml
components:
    blade:
        reference_axis: 
            grid: [0.0, ..., 1.0]
            x: [0.0, ..., -2.5]
            y: [0.0, ..., 0.]
            z: [0.0, ..., 120.]
        outer_shape:
            grid: [0.0, ..., 1.0]
            twist: [20., ..., 3.0]
            chord: [5., ..., 1.0]
            rthick: [1., ..., 0.2]
            section_offset_x: [2.5, ..., 0.3]
            section_offset_y: [0., ..., 0.0]
        aerodynamics:
            airfoils:
                - name: circular
                  spanwise_position: 0.0
                  configuration: [flat_cd]
                  weight: [1.0]
                - name: FFA-W3-211
                  spanwise_position: 0.5
                  configuration: [freetrans, fully_turb]
                  weight: [0.9, 0.1]
                - name: FFA-W3-211
                  spanwise_position: 1.0
                  configuration: [freetrans, fully_turb]
                  weight: [0.7, 0.3]
```

I agree that we ought to remove `rthick` since it makes the input ambiguous. with the addition of weights, we're actually arrived very close to the idea from Mike used in the Task 37 aero benchmark where the polar at each section is a linear combination of a given set of polars, except here, the polar at a section is only allow to interpolate in polars for a single shape. the nice thing with Mike's linear combination is that one could define actual polars quite coarsely, but control the weights with higher resolution and construct exactly the same polars as was done with interpolation as function of `rthick`. he then had two lists, one for aero and another for shape.

As to the twist needed by the `structure.elastic`, I'm not sure I follow. Is that because BeamDyn uses the blade root as reference frame and you need to provide the twist relative to that? If so, isn't it either way under-determined for a general curved blade since you'd have to make assumptions on how the section is otherwise oriented in space. but maybe I'm mis-understanding. It relates to what I mentioned about CPACS, that we could allow for optional specification for a quaternion / Euler angles to be specified for the geometric rotations of sections, and if left empty default to the definition in #97. In our own in-house geometry tool the inputs include `rot_x`, `rot_y`, and `rot_z`, and I only ever specified `rot_z` in the input file and computed the other rotations as outlined.
